'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),http=require('http'),cp=require('child_process');
const {getFreePort}=require('./free-port.js');
const WB=path.resolve(__dirname,'..','ruyi-workbench'),HOME=path.join(os.tmpdir(),'ruyi-multi-session-parallel');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let failures=0;const ok=(v,l)=>{if(v)console.log('PASS '+l);else{failures++;console.error('FAIL '+l);}};
function kill(p){if(p&&p.pid)try{cp.execFileSync('taskkill',['/PID',String(p.pid),'/T','/F'],{stdio:'ignore'});}catch{}}
function get(p,headers={}){return new Promise(resolve=>{const r=http.get({host:'127.0.0.1',port:WP,path:p,timeout:2000,headers},res=>{let b='';res.on('data',c=>b+=c);res.on('end',()=>{try{resolve(JSON.parse(b));}catch{resolve(null);}})});r.on('error',()=>resolve(null));r.on('timeout',()=>{r.destroy();resolve(null);});});}
function post(p,body,headers={}){return new Promise((resolve,reject)=>{const raw=JSON.stringify(body);const r=http.request({host:'127.0.0.1',port:WP,path:p,method:'POST',headers:{'content-type':'application/json','content-length':Buffer.byteLength(raw),...headers}},res=>{let b='';res.on('data',c=>b+=c);res.on('end',()=>{try{resolve(JSON.parse(b));}catch(e){reject(e);}})});r.on('error',reject);r.end(raw);});}
function stream(body,headers={}){return new Promise((resolve,reject)=>{const raw=JSON.stringify(body);const r=http.request({host:'127.0.0.1',port:WP,path:'/api/chat/stream',method:'POST',headers:{'content-type':'application/json','content-length':Buffer.byteLength(raw),...headers}},res=>{let b='',events=[];res.on('data',c=>{b+=c;let i;while((i=b.indexOf('\n'))>=0){const l=b.slice(0,i);b=b.slice(i+1);try{if(l.trim())events.push(JSON.parse(l));}catch{}}});res.on('end',()=>resolve(events));});r.on('error',reject);r.end(raw);});}
async function waitUp(){for(let i=0;i<50;i++){if(await get('/health'))return true;await sleep(100);}return false;}
(async()=>{const FP=await getFreePort(),WP=await getFreePort();fs.rmSync(HOME,{recursive:true,force:true});fs.mkdirSync(HOME,{recursive:true});fs.writeFileSync(path.join(HOME,'config.json'),JSON.stringify({configSchema:7,permissionMode:'bypass',defaultWorkspace:HOME,subagentMaxPerTurn:0,providers:[{id:'fake',label:'Fake',type:'openai-compat',baseUrl:`http://127.0.0.1:${FP}`,apiKey:'k',model:'fake-model'}],activeProvider:'fake',killOnDisconnect:true}));
const fake=cp.spawn(process.execPath,[path.join(__dirname,'fake-openai.js')],{env:{...process.env,FAKE_OPENAI_PORT:String(FP),FAKE_STREAM_DELAY_MS:'80'},windowsHide:true});const wb=cp.spawn(process.execPath,['app/server.js','serve','--port',String(WP)],{cwd:WB,env:{...process.env,RUYI_HOME:HOME},windowsHide:true});
try{ok(await waitUp(),'workbench starts');const html=await new Promise(resolve=>http.get({host:'127.0.0.1',port:WP,path:'/'},res=>{let b='';res.on('data',c=>b+=c);res.on('end',()=>resolve(b));}));const token=(html.match(/name="wcw-token"\s+content="([a-f0-9]+)"/)||[])[1],hdr={'x-wcw-token':token};
const s1=(await post('/api/sessions',{title:'one',cwd:HOME},hdr)).session.id;const p1=stream({sessionId:s1,message:'first long turn',cwd:HOME},hdr);await sleep(120);const s2=(await post('/api/sessions',{title:'two',cwd:HOME},hdr)).session.id;const p2=stream({sessionId:s2,message:'second long turn',cwd:HOME},hdr);const [e1,e2]=await Promise.all([p1,p2]);
ok(e1.some(e=>e.type==='result'&&e.ok===true)&&e2.some(e=>e.type==='result'&&e.ok===true),'both session turns complete without superseding each other');const start2=Date.parse((e2.find(e=>e.type==='process'&&e.state==='running')||{}).ts||0),end1=Date.parse((e1.find(e=>e.type==='result')||{}).ts||0);ok(start2>0&&end1>0&&start2<end1,'second session starts before the first session finishes (real overlap)');
const a1=await get('/api/sessions/'+s1,hdr),a2=await get('/api/sessions/'+s2,hdr);ok(a1.session.messages.some(m=>m.role==='assistant')&&a2.session.messages.some(m=>m.role==='assistant'),'both completed replies are persisted independently');
}finally{kill(wb);kill(fake);await sleep(200);fs.rmSync(HOME,{recursive:true,force:true});}console.log('\nMULTI SESSION PARALLEL E2E: '+(failures?`FAIL (${failures})`:'ALL PASS'));process.exitCode=failures?1:0;})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
